# Generated by Django 5.2.7 on 2025-12-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bot aktiv')),
                ('maintenance_message', models.TextField(blank=True, default="Bot texnik ishlar sababli vaqtincha to'xtatilgan. Iltimos keyinroq urinib ko'ring.", verbose_name='Texnik ishlar xabari')),
                ('card_number', models.CharField(max_length=50, verbose_name='Karta raqami')),
                ('card_holder', models.CharField(max_length=100, verbose_name='Karta egasi')),
                ('discount_active', models.BooleanField(default=True, verbose_name='Chegirma aktiv')),
                ('discount_percent', models.PositiveIntegerField(default=50, verbose_name='Chegirma foizi')),
                ('discount_duration', models.PositiveIntegerField(default=180, verbose_name='Chegirma muddati (sekund)')),
                ('free_trial_days', models.PositiveIntegerField(default=7, verbose_name='Bepul kunlar soni')),
                ('referral_active', models.BooleanField(default=True, verbose_name='Referal aktiv')),
                ('referral_bonus', models.PositiveIntegerField(default=1, verbose_name='Referal bonus (kun)')),
                ('admin_contact', models.CharField(blank=True, default='', max_length=100, verbose_name='Admin kontakt')),
            ],
            options={
                'verbose_name': 'Bot sozlamalari',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('all', 'Hammaga'), ('premium', 'Premium foydalanuvchilar'), ('regular', 'Oddiy foydalanuvchilar')], default='all', max_length=20, verbose_name='Kimga')),
                ('content_type', models.CharField(choices=[('text', 'Matn'), ('photo', 'Rasm'), ('video', 'Video'), ('document', 'Fayl')], default='text', max_length=20, verbose_name='Kontent turi')),
                ('text', models.TextField(blank=True, default='', verbose_name='Xabar matni')),
                ('file_id', models.CharField(blank=True, default='', max_length=255, verbose_name='File ID')),
                ('is_advertisement', models.BooleanField(default=False, verbose_name='Reklama (premium ga bormaydi)')),
                ('buttons', models.JSONField(blank=True, null=True, verbose_name='Inline tugmalar')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Jami foydalanuvchilar')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Yuborildi')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Xato')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugallandi')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='users.user', verbose_name='Kim yubordi')),
            ],
            options={
                'verbose_name': 'Xabar yuborish',
                'verbose_name_plural': 'Xabar yuborishlar',
                'ordering': ['-started_at'],
            },
        ),
    ]
