# Generated by Django 5.0.6 on 2025-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='channel_link',
            field=models.URLField(blank=True, default='', verbose_name='Kanal linki'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='channel_name',
            field=models.CharField(blank=True, default='Bizning kanal', max_length=100, verbose_name='Kanal nomi'),
        ),
    ]
