# Generated by Django 5.0.6 on 2025-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_channel_link_to_botsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('welcome', 'Salom xabari'), ('subscription_required', 'Obuna talab qilish'), ('subscription_success', 'Obuna muvaffaqiyatli'), ('premium_required', 'Premium talab qilish'), ('premium_info', "Premium ma'lumot"), ('premium_success', 'Premium muvaffaqiyatli'), ('payment_instructions', "To'lov ko'rsatmalari"), ('payment_pending', "To'lov kutilmoqda"), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi"), ('movie_not_found', 'Kino topilmadi'), ('search_prompt', "Qidiruv so'rovi"), ('profile_info', "Profil ma'lumoti"), ('referral_info', "Referal ma'lumoti"), ('ban_message', 'Ban xabari'), ('maintenance', 'Texnik ishlar')], max_length=50, unique=True, verbose_name='Xabar turi')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Xabar matni')),
                ('placeholders_help', models.TextField(blank=True, default='', verbose_name='Placeholder yordam')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Xabar shabloni',
                'verbose_name_plural': 'Xabar shablonlari',
                'ordering': ['message_type'],
            },
        ),
    ]
