# Generated by Django 5.2.7 on 2025-12-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('emoji', models.CharField(blank=True, default='', max_length=10, verbose_name='Emoji')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kino kodi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi (original)')),
                ('title_uz', models.CharField(blank=True, default='', max_length=255, verbose_name="Nomi (o'zbekcha)")),
                ('file_id', models.CharField(max_length=255, verbose_name='Telegram File ID')),
                ('thumbnail_file_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Thumbnail File ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yili')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p HD'), ('1080p', '1080p Full HD'), ('4k', '4K Ultra HD')], default='720p', max_length=10, verbose_name='Sifati')),
                ('language', models.CharField(choices=[('uzbek', "O'zbek tilida"), ('rus', 'Rus tilida'), ('eng', 'Ingliz tilida'), ('turk', 'Turk tilida'), ('korea', 'Koreys tilida'), ('other', 'Boshqa')], default='uzbek', max_length=20, verbose_name='Tili')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium kino')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_movies', to='users.user', verbose_name="Kim qo'shgan")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
