# Generated by Django 5.2.7 on 2025-12-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0002_user_joined_from_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(choices=[('usa', '🇺🇸 AQSH'), ('korea', '🇰🇷 Janubiy Koreya'), ('india', '🇮🇳 Hindiston'), ('turkey', '🇹🇷 Turkiya'), ('russia', '🇷🇺 Rossiya'), ('uzbekistan', "🇺🇿 O'zbekiston"), ('uk', '🇬🇧 Buyuk Britaniya'), ('france', '🇫🇷 Fransiya'), ('japan', '🇯🇵 Yaponiya'), ('china', '🇨🇳 Xitoy'), ('other', '🌍 Boshqa')], default='usa', max_length=20, verbose_name='Davlati'),
        ),
        migrations.CreateModel(
            name='SavedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Saqlangan vaqt')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='movies.movie', verbose_name='Kino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_movies', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Saqlangan kino',
                'verbose_name_plural': 'Saqlangan kinolar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
