# Generated by Django 5.2.7 on 2025-12-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('days', models.PositiveIntegerField(verbose_name='Kunlar soni')),
                ('price', models.PositiveIntegerField(verbose_name="Narxi (so'm)")),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True, verbose_name="Chegirmali narx (so'm)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'ordering': ['order', 'days'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name="To'langan summa")),
                ('is_discounted', models.BooleanField(default=False, verbose_name="Chegirma qo'llandi")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan')], default='pending', max_length=20, verbose_name='Holat')),
                ('screenshot_file_id', models.CharField(max_length=255, verbose_name='Screenshot File ID')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Admin izohi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to='users.user', verbose_name='Kim tasdiqladi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.user', verbose_name='Foydalanuvchi')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.tariff', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
