# Generated by Django 5.2.7 on 2025-12-23 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0003_user_premium_first_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name="To'lov summasi")),
                ('is_discounted', models.BooleanField(default=False, verbose_name='Chegirma')),
                ('message_id', models.BigIntegerField(verbose_name='Xabar ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('expires_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_sessions', to='payments.tariff', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_sessions', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "To'lov sessiyasi",
                'verbose_name_plural': "To'lov sessiyalari",
                'ordering': ['-created_at'],
            },
        ),
    ]
