# Generated by Django 5.2.7 on 2025-12-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_pending_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_messages',
            field=models.JSONField(blank=True, null=True, verbose_name='Admin xabarlari'),
        ),
    ]
