# Generated by Django 5.2.7 on 2025-12-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('premium_expires', models.DateTimeField(blank=True, null=True, verbose_name='Premium tugash vaqti')),
                ('free_trial_expires', models.DateTimeField(blank=True, null=True, verbose_name='Bepul muddat tugashi')),
                ('referral_code', models.CharField(max_length=10, unique=True, verbose_name='Referal kod')),
                ('movies_watched', models.PositiveIntegerField(default=0, verbose_name="Ko'rilgan kinolar")),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('ban_reason', models.TextField(blank=True, null=True, verbose_name='Bloklash sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users.user', verbose_name='Taklif qilgan')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='moderator', max_length=20, verbose_name='Rol')),
                ('can_add_movies', models.BooleanField(default=False, verbose_name="Kino qo'sha oladi")),
                ('can_broadcast', models.BooleanField(default=False, verbose_name='Xabar yuborishi mumkin')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Userlarni boshqaradi')),
                ('can_manage_payments', models.BooleanField(default=False, verbose_name="To'lovlarni boshqaradi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
    ]
