# Generated by Django 5.2.7 on 2025-12-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_channel_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_from_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_users', to='channels.channel', verbose_name='Qaysi kanaldan kelgan'),
        ),
    ]
