# Generated by Django 5.2.7 on 2025-12-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_joined_from_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_first_view',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Premium birinchi ko'rilgan"),
        ),
    ]
