# Generated by Django 5.2.7 on 2025-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Kanal ID')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='Username')),
                ('title', models.CharField(max_length=255, verbose_name='Kanal nomi')),
                ('invite_link', models.URLField(verbose_name='Havola')),
                ('channel_type', models.CharField(choices=[('public', 'Ochiq kanal'), ('private', 'Yopiq kanal'), ('group', 'Guruh'), ('external', 'Tashqi platforma')], default='public', max_length=20, verbose_name='Turi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
            ],
            options={
                'verbose_name': 'Kanal',
                'verbose_name_plural': 'Kanallar',
                'ordering': ['order', 'title'],
            },
        ),
    ]
