# Generated by Django 5.2.7 on 2025-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('telegram_channel', 'Telegram kanal'), ('telegram_group', 'Telegram guruh'), ('telegram_bot', 'Telegram bot'), ('instagram', 'Instagram'), ('external', 'Tashqi platforma')], default='public', max_length=20, verbose_name='Turi'),
        ),
    ]
