# Generated by Django 5.2.7 on 2025-12-22 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_channel_type'),
        ('users', '0003_user_premium_first_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Obuna vaqti')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='channels.channel', verbose_name='Kanal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_subscriptions', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kanal obunasi',
                'verbose_name_plural': 'Kanal obunalari',
                'ordering': ['-subscribed_at'],
                'unique_together': {('channel', 'user')},
            },
        ),
    ]
